name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and Push Book Service
      uses: docker/build-push-action@v2
      with:
        context: ./book-service
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/book-service:latest
    
    - name: Build and Push Loan Service
      uses: docker/build-push-action@v2
      with:
        context: ./loan-service
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/loan-service:latest
        
    - name: Build and Push Frontend
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest